<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>game_frame</name>
   <tag></tag>
   <elementGuidId>4ba133b5-3522-4552-b810-7e8c1ce435ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.game</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
