<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_casino_menu</name>
   <tag></tag>
   <elementGuidId>6e92c044-4523-4491-b27c-d17669733201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div#navigation</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
