<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lottery_frame</name>
   <tag></tag>
   <elementGuidId>ec1c6dc4-b4af-4fd8-94cb-f79f0a8f0021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lottery-tickets</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
