<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_country_phone_code</name>
   <tag></tag>
   <elementGuidId>d2929d60-1939-480b-a022-0e0479a052b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.phone-number-input.phone-number-input--small</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @class = 'phone-number-input phone-number-input--small']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+46</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone-number-input phone-number-input--small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;logged-out&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal__wrapper&quot;]/div[@class=&quot;modal__container&quot;]/div[@class=&quot;modal__body&quot;]/form[@class=&quot;phone&quot;]/section[@class=&quot;phone__body&quot;]/div[@class=&quot;row phone-row&quot;]/div[@class=&quot;column column--wrap&quot;]/input[@class=&quot;phone-number-input phone-number-input--small&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div[2]/div/div[2]/form/section/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
